### ISSUE TITLE
Propagate attributes into the Inner struct

### ISSUE THREAD

**Issue by dtolnay** [kardeiz/serde_tuple#1]
To support the same attributes as serde_derive, it should be sufficient to copy any attributes on the input struct + input fields into attributes of the Inner struct + inner fields.

```rust
#[derive(Deserialize_tuple)]
#[serde(bound = "...")]
struct S<T> {
    a: T,
    #[serde(skip)]
    b: T,
}

// -->

#[derive(Deserialize)]
#[serde(rename = "S")]
#[serde(bound = "...")]
struct Inner<T>(T, #[serde(skip)] T);
```

**Comment by kardeiz** [comment]
Thanks for the issue! This is fixed in [`0.2.1`](https://crates.io/crates/serde_tuple/0.2.1).

I had to add a line to detect whether there was a `#[serde(rename="X")]` in the attributes and omit the internal rename if so.

I'm closing this, but let me know if you have any other issues. Thanks again!

**Comment by dtolnay** [comment]
Please also add a test case that exercises a field attribute, like #[serde(skip)].

**Comment by kardeiz** [comment]
Argh, sorry, missed the part about field attributes. I've added these in [`0.2.2`](https://crates.io/crates/serde_tuple/0.2.2) and updated the example.

**Comment by dtolnay** [comment]
Nice, thanks for the quick fix.

FYI @nox (https://github.com/servo/euclid/issues/322)

**Comment by nox** [comment]
Thanks @dtolnay! And thanks @kardeiz for such a quick answer.
